### ISSUE TITLE
Feature highlighting across tiles inconsistent

### ISSUE THREAD

**Issue by gusmacaulay** [consbio/Leaflet.UTFGrid#3]
Hi - I'm using this plugin with tilestache and it's working pretty well - but the highlighted features are only sometimes showing in tiles outside the mouseover tile, the docs suggest there is an option for this 'Optionally can highlight entire feature, not just the portion of it within a single tile'  - but I couldn't find anything.

**Comment by brendan-ward** [comment]
@gusmacaulay, the "optionally" refers to highlighting or not; there isn't an option for only highlighting the part in a given tile.  This was written to be in contrast to the other implementation I found, which only highlights the part in a given tile.

Can you share a publicly accessible URL to your tile service, so I can test and try to find the underlying issue?  A small extract of the tile stack as a zip file or mbtiles file would be fine too, so long as it shows the problem.

**Comment by gusmacaulay** [comment]
@brendan-ward - Thanks, I looked into my utfgrids and figured out the issue - I was trying to use a key that wasn't unique, the result was quite muddled.
